GET http://127.0.0.1:6001/api/v1/appInfo
### 
POST http://127.0.0.1:6001/api/v1/auth/login
content-type: application/json

{
  "email": "admin@livfarm.com",
  "password": "connect2020"
}
###
GET http://34.64.111.112:6001/api/v1/inventories/61e2d76775a18b03cd9c1fbc

###
GET http://127.0.0.1:6001/api/v1/products/61e2d75e75a18b03cd9c1f93/reviews